[package]
name = "mergeusc_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
mergeusc_core = { path = "../MergeUSC_Core" }
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"