name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu

      - name: Debug directory structure
        run: |
          find ./crates -type d | sort
          ls -la ./crates

      - name: Standardize directory structure
        run: |
          # コアライブラリの実際のディレクトリ名を見つける
          CORE_DIR=$(find ./crates -maxdepth 1 -type d -iname "merge*core" | head -n 1)
          if [ -z "$CORE_DIR" ]; then
            echo "ERROR: Could not find core directory!"
            exit 1
          fi
          CORE_NAME=$(basename "$CORE_DIR")
          echo "Found core directory: $CORE_NAME"
          
          # 統一したディレクトリ名を使用する
          STANDARD_CORE_NAME="mergeusc_core"
          if [ "$CORE_NAME" != "$STANDARD_CORE_NAME" ]; then
            echo "Creating symbolic link from $CORE_NAME to $STANDARD_CORE_NAME"
            ln -sf "$CORE_NAME" "./crates/$STANDARD_CORE_NAME"
          fi

      - name: Create workspace Cargo.toml
        run: |
          cat > Cargo.toml << 'EOF'
          [workspace]
          members = [
              "crates/cli"
          ]
          resolver = "2"

          [profile.release]
          opt-level = 3
          lto = true
          codegen-units = 1
          EOF
          echo "Created workspace Cargo.toml"

      - name: Update cli Cargo.toml
        run: |
          # cliのCargo.tomlを更新して確実にビルドできるようにする
          sed -i 's|path = "../MergeUSC_Core"|path = "../mergeusc_core"|' crates/cli/Cargo.toml

      - name: Build CLI
        run: |
          cd crates/cli
          cargo build --release

      - name: Package
        run: |
          mkdir -p release
          cp crates/cli/target/release/mergeusc_cli release/mergeusc_cli-linux
          cd release && tar -czf mergeusc_cli-linux.tar.gz mergeusc_cli-linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mergeusc_cli-linux
          path: release/mergeusc_cli-linux.tar.gz
          retention-days: 1

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-msvc

      - name: Debug directory structure
        run: |
          Get-ChildItem -Path ./crates -Recurse -Directory | Select-Object FullName

      - name: Standardize directory structure
        run: |
          # Windowsでの大文字小文字の問題を解決
          $coreDir = Get-ChildItem -Path ./crates -Directory | Where-Object { $_.Name -like "*merge*core*" } | Select-Object -First 1
          
          if ($null -eq $coreDir) {
            Write-Error "Could not find core directory!"
            exit 1
          }
          
          Write-Output "Found core directory: $($coreDir.Name)"
          
          # 正規のディレクトリ名として小文字バージョンを使用
          New-Item -Path ./crates -Name "mergeusc_core" -ItemType Junction -Target $coreDir.FullName -Force
          
          # ワークスペースがクリーンであることを確認
          if (Test-Path ./crates/MergeUSC_Core -PathType Container) {
            Write-Output "Removing MergeUSC_Core directory from workspace members"
            Remove-Item ./crates/MergeUSC_Core -Force -Recurse
          }

      - name: Create workspace Cargo.toml
        run: |
          @"
          [workspace]
          members = [
              "crates/cli"
          ]
          resolver = "2"

          [profile.release]
          opt-level = 3
          lto = true
          codegen-units = 1
          "@ | Set-Content -Path Cargo.toml -Encoding UTF8

      - name: Update cli Cargo.toml
        run: |
          # cliのCargo.tomlを更新
          (Get-Content crates/cli/Cargo.toml) -replace 'path = "../MergeUSC_Core"', 'path = "../mergeusc_core"' | Set-Content crates/cli/Cargo.toml

      - name: Build CLI
        run: |
          cd crates/cli
          cargo build --release

      - name: Package
        run: |
          New-Item -Path release -ItemType Directory -Force
          Copy-Item crates/cli/target/release/mergeusc_cli.exe -Destination release/mergeusc_cli-windows.exe
          cd release
          7z a -tzip mergeusc_cli-windows.zip mergeusc_cli-windows.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mergeusc_cli-windows
          path: release/mergeusc_cli-windows.zip
          retention-days: 1

  create-release:
    name: Create GitHub Release
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: mergeusc_cli-linux
          path: ./artifacts

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: mergeusc_cli-windows
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: true
          files: |
            ./artifacts/mergeusc_cli-linux.tar.gz
            ./artifacts/mergeusc_cli-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}